//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.DBContexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posicion
    {
        public long idPosicion { get; set; }
        public int idEntidad { get; set; }
        public int idEquipo { get; set; }
        public double latitud { get; set; }
        public double longitud { get; set; }
        public System.DateTime fechaPosicion { get; set; }
        public int status { get; set; }
        public int evento { get; set; }
        public double velocidad { get; set; }
        public string rumbo { get; set; }
        public Nullable<int> rumboGrados { get; set; }
        public Nullable<int> posicionGPS { get; set; }
        public Nullable<int> edadDato { get; set; }
        public Nullable<int> difusionHorizontal { get; set; }
        public System.DateTime fechaAlta { get; set; }
        public Nullable<int> idPosicionOrigen { get; set; }
    
        public virtual Entidad Entidad { get; set; }
        public virtual Equipo Equipo { get; set; }
    }
}
